name: Docker Image CI for PR

on: pull_request

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to docker.pkg.github.com
      run:  echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Build the Docker image
      env:
        pr_number: ${{ format('pr{0}', {{jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH"}}}}
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/dbalc:{{ pr_number }} .
    - name: Push image to GitHub Packages
      run: docker push docker.pkg.github.com/${{ github.repository }}/dbalc:{{ pr_number }}
